baseURL = 'https://elegant-tesla-d6e95b.netlify.app/'
languageCode = 'en-us'
title = 'DAO Backend Docs'
theme = "ace-documentation"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true


