baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'DAO Backend Docs'
theme = "ace-documentation"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true


